/**
 * Activity Export Script
 *
 * Exports recent activity from the SQLite journal to a Markdown file
 * for consumption by Obsidian Dataview queries.
 */

import { ConfigService } from "../src/config/service.ts";
import { DatabaseService } from "../src/services/db.ts";
import { join } from "@std/path";

async function main() {
  const configService = new ConfigService();
  const config = configService.get();
  const db = new DatabaseService(config);

  try {
    const activities = db.getRecentActivity(100);

    const tableRows = activities.map((a) => {
      const time = new Date(a.timestamp).toLocaleString();
      const target = a.target || "-";
      const actor = a.actor || "system";
      const action = a.action_type;
      const trace = a.trace_id.substring(0, 8);

      return `| ${time} | ${actor} | ${action} | ${target} | ${trace} |`;
    });

    const markdown = [
      "# Activity Log Export",
      "",
      "This file is automatically generated for Obsidian Dataview consumption.",
      "",
      "| Timestamp | Actor | Action | Target | Trace |",
      "| :--- | :--- | :--- | :--- | :--- |",
      ...tableRows,
      "",
      `*Last updated: ${new Date().toLocaleString()}*`,
    ].join("\n");

    const exportPath = join(config.system.root, "System", "activity_export.md");
    await Deno.writeTextFile(exportPath, markdown);

    console.log(`✅ Activity exported to ${exportPath}`);
  } catch (error) {
    console.error("❌ Export failed:", error);
    Deno.exit(1);
  } finally {
    db.close();
  }
}

if (import.meta.main) {
  main();
}
